### ISSUE TITLE
Fail when trying to publish existing version

### ISSUE THREAD

**Issue by jay-oswald** [primer/publish#24]
Similar to #10 

I am using this package to publish other things to the NPM, at the moment if you try to publish without a version bump the package runs, and in the log it says something like

```
[publish] skipping "npm version" because "0.1.4" matches package.json
[publish] 0.1.4 is already published
```

It would be great if when this happened the action failed, so you know it didn't publish, and you forgot a version bump or something.

**Comment by cinderblock** [comment]
This is intentional behavior.
From README, emphasis mine.
> **If the version in package.json is already published, we exit with a 0 code.** Previously, we exited with a 78 code, which was Actions v1-speak for "neutral", but this has been removed from Actions v2.

I personally want this behavior. I don't want it to look like my builds are failing even though they worked fine and I haven't decided it's time for a version bump.

To be fair, I see merit in adding this as an optional feature.
